<?php
/**
 * @description Uploader template
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 */
?>

<?php
/**
 * @var \Bina\CustomerFile\Block\Uploader $block
 */
?>

<fieldset class="fieldset" id="<?= $block->getAttributeCode() ?>">
    <legend class="legend">
        <span><?= $block->escapeHtml($block->getAttributeLabel()) ?></span>
    </legend>

    <div class="field uploader-container">
        <!-- ko scope: '<?= $block->escapeJs($block->getUploaderId()) ?>' -->
            <!-- ko template: getTemplate() --><!-- /ko -->
        <!-- /ko -->
    </div>
</fieldset>

<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "<?= $block->escapeJs($block->getUploaderId()) ?>": {
                    "component"        : "Bina_CustomerFile/js/form/element/uploader",
                    "label"            : "<?php echo $block->getAttributeLabel() ?>",
                    "allowedExtensions": <?php echo $block->getAttributeAllowedExtensionsJson() ?>,
                    "fieldAttribute"   : "<?php echo $block->getAttributeCode() ?>",
                    "value"            : <?php echo $block->getAttributeDataJson() ?>,
                    "uploaderConfig"   : {
                        "url": "<?php echo $block->getUploadUrl() ?>"
                    }
                }
            }
        }
    }
}
</script>